- name: Ensure that the inventory hostname points to the dns record
  community.general.cloudflare_dns:
    zone: "{{ dns_cf_zone | mandatory }}"
    record: "{{ dns_cf_record }}"
    type: "{{ dns_cf_type  }}"
    value: "{{ dns_cf_value }}"
    state: "{{ state  }}"
    api_token: "{{ lookup('ansible.builtin.env', 'CF_KEY') }}"
  register: cf_record