- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_KEY') }}"
    name: "{{ inventory_hostname }}"
    size: "{{ do_droplet_size }}"
    region: "{{ do_droplet_region }}"
    image: "{{ do_droplet_image }}"
    wait_timeout: 500
    ssh_keys: [ "{{ primary_ssh_key }}" ]
  register: do_droplet